
logging:
  level:
    root: info


spring:
  #file upload 용량 제한하기
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB
  application:
    name: articles
  # Database 설정
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SPRING_BOOT
    password: SPRING_BOOT_1234
    
# DB Query 동작과 결과를 받아오기 위한 설정 정보 작성.
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/**/dao/mapper/*DaoMapper.xml
  

# Custom 환경 설정
# 사용하려는 Spring Bean 에서 @Value 로 사용 가능 
app:
  multipart:
    store-path: uploadFiles
  encrypt:
    aes:
      key: abcde12345abcde12345abcde12345zz   

  
  
  
  